# Physical properties of Ou 5

In [28]:
import numpy as np
import pyneb as pn
from astropy import constants
import astropy.units as u

## Ionization balance for H and He

Note it is necessary to set these data files before we create the RecAtoms, otherwise the total recombination rate does not work

In [2]:
pn.atomicData.setDataFile('h_i_trc_SH95-caseB.dat')
pn.atomicData.setDataFile('he_ii_trc_SH95-caseB.dat')

### Temperature and density samples

In [19]:
temps = np.array([500, 1000, 6000, 10000, 13000])
dens = np.array([100, 1000, 10000])

### H alpha emission coefficient versus temperature

We need this to estimate the emission measure of the differernt nebular components from the observed surface brightness

In [3]:
H1 = pn.RecAtom('H', 1)

Case B recombination rate

In [37]:
alpha_H_B = H1.getTotRecombination(tem=temps[:, None], den=dens)
alpha_H_B 

array([[2.49300000e-12, 2.57300000e-12, 2.72000000e-12],
       [1.51200000e-12, 1.53500000e-12, 1.57900000e-12],
       [3.96037430e-13, 3.96922668e-13, 3.98583076e-13],
       [2.58500000e-13, 2.58800000e-13, 2.59400000e-13],
       [2.07774355e-13, 2.08031331e-13, 2.08231331e-13]])

H alpha emissivity in erg.s-1.cm3

In [38]:
j_6563 = H1.getEmissivity(tem=temps, den=dens, label="3_2")
j_6563

array([[4.54200000e-24, 4.61200000e-24, 4.75800000e-24],
       [2.61600000e-24, 2.62800000e-24, 2.65500000e-24],
       [5.65600000e-25, 5.65150000e-25, 5.64500000e-25],
       [3.53600000e-25, 3.53400000e-25, 3.53000000e-25],
       [2.75338462e-25, 2.75138462e-25, 2.74884615e-25]])

Density dependence (columns) is negligible: 2 or 3% positive gradient from 100 pcc to 1e4 pcc at low T, 0.02% negative gradient at high T. 

So constant pressure will have a slighty steeper temperature dependence than constant density

Energy of an H alpha photon

In [39]:
E_6563 = (constants.c * constants.h / (H1.getWave(3, 2) * u.angstrom)).cgs
E_6563.value

3.0268193154262724e-12

Fraction of Case B recombinations that produce H alpha

In [41]:
f_6563 = j_6563 / E_6563.value / alpha_H_B
f_6563

array([[0.60191942, 0.59219265, 0.57792175],
       [0.57160952, 0.56562746, 0.55551514],
       [0.47183122, 0.47040435, 0.46790598],
       [0.4519238 , 0.45114461, 0.44959165],
       [0.43781279, 0.43695434, 0.43613191]])

So the fraction $f_{6563}$ is about 0.6 for T <= 1000 K, as opposed to 0.45 for 10,000 K.  And with almost no dependence on density

And do the Balmer decrement

In [58]:
j_4861 = H1.getEmissivity(tem=temps, den=dens, label="4_2")
j_6563 / j_4861

array([[3.98071867, 3.85296575, 3.67981439],
       [3.66181411, 3.58869316, 3.48288076],
       [2.99417681, 2.98153521, 2.96092316],
       [2.86315789, 2.85691188, 2.84677419],
       [2.81399371, 2.80927734, 2.8013609 ]])

### He++ recombination coefficient versus temperature

In [6]:
He2 = pn.RecAtom("He", 2)

In [42]:
alpha_He_B = He2.getTotRecombination(tem=temps[:, None], den=dens)
alpha_He_B

array([[1.26200000e-11, 1.31400000e-11, 1.41200000e-11],
       [7.82600000e-12, 7.98400000e-12, 8.27700000e-12],
       [2.25362013e-12, 2.25992217e-12, 2.27332489e-12],
       [1.53300000e-12, 1.53600000e-12, 1.54100000e-12],
       [1.26064500e-12, 1.26164500e-12, 1.26464500e-12]])

In [44]:
j_6560 = He2.getEmissivity(tem=temps, den=dens, label="6_4")
j_6560

array([[2.43300000e-24, 2.54000000e-24, 2.71500000e-24],
       [1.46400000e-24, 1.49100000e-24, 1.53400000e-24],
       [3.30350000e-25, 3.30150000e-25, 3.29350000e-25],
       [2.02700000e-25, 2.02400000e-25, 2.01700000e-25],
       [1.55361538e-25, 1.55061538e-25, 1.54507692e-25]])

In [16]:
He2.getWave(6, 4)

6559.876637343726

Energy of an He II 6560 photon

In [45]:
E_6560 = (constants.c * constants.h / (He2.getWave(6, 4) * u.angstrom)).cgs
E_6560.value

3.0281756303778526e-12

Fraction of He++ Case B recombinations that produce He II 6560

In [46]:
f_6560 = j_6560 / E_6560.value / alpha_He_B
f_6560

array([[0.06366514, 0.06383477, 0.06349713],
       [0.06177606, 0.0616703 , 0.06120281],
       [0.04840749, 0.04824327, 0.04784264],
       [0.04366471, 0.04351492, 0.04322373],
       [0.04069768, 0.0405869 , 0.04034599]])

So this is about 11 times smaller than for H alpha, with a very similar T dependence

#### Repeat for the 4686 line

In [47]:
j_4686 = He2.getEmissivity(tem=temps, den=dens, label="4_3")
j_4686

array([[2.25200000e-23, 2.27100000e-23, 2.31800000e-23],
       [1.27400000e-23, 1.26800000e-23, 1.26400000e-23],
       [2.52200000e-24, 2.50550000e-24, 2.47900000e-24],
       [1.51600000e-24, 1.50800000e-24, 1.49500000e-24],
       [1.15458462e-24, 1.14979231e-24, 1.14127692e-24]])

In [48]:
He2.getWave(4, 3)

4685.55411681253

In [49]:
E_4686 = (constants.c * constants.h / (He2.getWave(4, 3) * u.angstrom)).cgs
E_4686.value

4.2395110751602196e-12

In [50]:
f_4686 = j_4686 / E_4686.value / alpha_He_B
f_4686

array([[0.42091389, 0.40766741, 0.38722462],
       [0.3839846 , 0.37461309, 0.36021214],
       [0.26396637, 0.2615081 , 0.25721675],
       [0.23326054, 0.23157643, 0.22883517],
       [0.21603155, 0.21496436, 0.21286616]])

So this is about half the H alpha value at warm temperatures, with a bit steeper T dependence so it is 2/3 at cool temperatures. It also has more of a density dependence than the other fractions, but it is still not significant.

### Estimating Q_3 

The H alpha luminosity can be estimated from the extinction-corrected flux (see calculation in org file)

In [51]:
Flux_ha = 3.8e-12 * u.erg / u.s / u.cm**2

Uncertainty in flux is about 40%

In [56]:
D_kpc = 4
L_ha = (Flux_ha * (4 * np.pi * (D_kpc * u.kpc)**2)).cgs
L_ha 

<Quantity 7.27469071e+33 erg / s>

Or in solar units

In [57]:
L_ha / constants.L_sun.cgs

<Quantity 1.90038942>

Observed 100 F(4686)/Hb = 71 from Corradi (2015) and that hardly needs correcting for extinction. We can just use the theoretical Ha/Hb ratio = 2.9 at warm temperatures, although it can be up to 4 at cool temperatures. We use 3

In [59]:
L_4686 = L_ha * 0.71 / 3
L_4686

<Quantity 1.7216768e+33 erg / s>

In [62]:
Q_3 = alpha_He_B * L_4686 / (j_4686 * u.erg)

In [64]:
Q_3.value

array([[9.64811778e+44, 9.96161743e+44, 1.04875222e+45],
       [1.05760146e+45, 1.08405896e+45, 1.12739865e+45],
       [1.53846372e+45, 1.55292579e+45, 1.57883450e+45],
       [1.74098320e+45, 1.75364428e+45, 1.77465147e+45],
       [1.87983039e+45, 1.88916286e+45, 1.90778409e+45]])

So it about 1e45 per second. Now to check against the cloudy models. **Note that it will scale with the distance as $D^2$ so it would be two times smaller for the Jones distance**

Repeat for the 6560 line. We get the ratio over H alpha from the 04-01 notebook. Multiplying the scale that we found when we normalized the co-added bgsub image by the sumscale that we calculated when plotting the spatial profile. This means that we are calculating the ratio for the inner lobes+ring close to the axis

In [65]:
R_6560_6563 = (3.2187782450199 / 66.59484446105931) * (3.8117776 / 5.6593223)
R_6560_6563

0.0325546907527186

In [66]:
L_6560 = L_ha * R_6560_6563
L_6560

<Quantity 2.36825306e+32 erg / s>

In [67]:
Q_3r = alpha_He_B * L_6560/ (j_6560 * u.erg)
Q_3r.value

array([[1.22841569e+45, 1.22515139e+45, 1.23166605e+45],
       [1.26598009e+45, 1.26815107e+45, 1.27783772e+45],
       [1.61560248e+45, 1.62110181e+45, 1.63467698e+45],
       [1.79108631e+45, 1.79725134e+45, 1.80935943e+45],
       [1.92166376e+45, 1.92690893e+45, 1.93841442e+45]])

In [68]:
Q_3r.value / Q_3.value

array([[1.27321796, 1.22987195, 1.17441091],
       [1.19702944, 1.16981744, 1.13343911],
       [1.05014012, 1.04390165, 1.03536943],
       [1.02877863, 1.02486654, 1.01955762],
       [1.0222538 , 1.01998032, 1.01605545]])

So this gives a very similar value if T is warm, up to about 1.2 times larger if T is cool. So that is very gratifying that it comes out the same.

# Sources of atomic data

In [5]:
H1.printSources()

Storey and Hummer 1995, MNRAS, 272, 41
Ref. 15291 of NIST 2014 (try this: http://physics.nist.gov/cgi-bin/ASBib1/get_ASBib_ref.cgi?db=el&db_id=15291&comment_code=&element=H&spectr_charge=1&


In [8]:
He2.printSources()

Storey and Hummer 1995
Ref.  of NIST 2014 (try this: http://physics.nist.gov/cgi-bin/ASBib1/get_ASBib_ref.cgi?db=el&db_id=&comment_code=&element=He&spectr_charge=2&
Ref. 3620c107 of NIST 2014 (try this: http://physics.nist.gov/cgi-bin/ASBib1/get_ASBib_ref.cgi?db=el&db_id=3620c107&comment_code=&element=He&spectr_charge=2&


In [9]:
pn.atomicData.getAllAvailableFiles("He2")

['* 3he_ii_atom_cloudy.dat',
 '* 3he_ii_coll_cloudy.dat',
 '* he_ii_rec_SH95.hdf5',
 '* he_ii_trc_SH95-caseB.dat',
 'he_ii_rec_P91.func',
 'he_ii_rec_SH95-caseA.fits',
 'he_ii_rec_SH95-caseA.hdf5',
 'he_ii_rec_SH95.fits',
 'he_ii_trc_SH95-caseA.dat']

In [10]:
He2.getTotRecombination??

Signature: He2.getTotRecombination(tem, den, method='linear')
Docstring:
Return the total recombination coefficient. The case (A or B) is set by selecting the corresponding trc file.

Parameters:
    tem:  temperature 
    den: density
    method:    interpolation method in the grid ('linear' = default, 'nearest', 'cubic')    
    
**Usage:**
    atomicData.setDataFile('h_i_trc_SH95-caseA.dat')
    h1.getTotRecombination(tem=10000, den=5.e3)
        
Source:   
    def getTotRecombination(self, tem, den, method='linear'):
        """
        Return the total recombination coefficient. The case (A or B) is set by selecting the corresponding trc file.
    
        Parameters:
            tem:  temperature 
            den: density
            method:    interpolation method in the grid ('linear' = default, 'nearest', 'cubic')    
            
        **Usage:**
            atomicData.setDataFile('h_i_trc_SH95-caseA.dat')
            h1.getTotRecombination(tem=10000, den=5.e3)
           

In [12]:
pn.atomicData.getDataFile()

{'H1': {'rec': 'h_i_rec_SH95.hdf5', 'trc': 'h_i_trc_SH95-caseB.dat'},
 'He1': {'rec': 'he_i_rec_Pal12-Pal13.hdf5'},
 'He2': {'rec': 'he_ii_rec_SH95.hdf5', 'trc': 'he_ii_trc_SH95-caseB.dat'},
 'Al2': {'atom': 'al_ii_atom_JSP86-HK87-VVF96-KS86.dat',
  'coll': 'al_ii_coll_KHAF92-TBK85-TBK84.dat'},
 'Ar2': {'atom': 'ar_ii_atom_Bal06.dat', 'coll': 'ar_ii_coll_PB95.dat'},
 'Ar3': {'atom': 'ar_iii_atom_MB09.dat', 'coll': 'ar_iii_coll_MB09.dat'},
 'Ar4': {'atom': 'ar_iv_atom_RGJ19.dat', 'coll': 'ar_iv_coll_RB97.dat'},
 'Ar5': {'atom': 'ar_v_atom_LL93-MZ82-KS86.dat',
  'coll': 'ar_v_coll_GMZ95.dat'},
 'Ba2': {'atom': 'ba_ii_atom_C04.dat', 'coll': 'ba_ii_coll_SB98.dat'},
 'Ba4': {'atom': 'ba_iv_atom_BHQZ95.dat', 'coll': 'ba_iv_coll_SB98.dat'},
 'C1': {'atom': 'c_i_atom_FFS85.dat',
  'coll': 'c_i_coll_JBK87-PA76.dat',
  'rec': 'c_i_rec_P91.func'},
 'C2': {'atom': 'c_ii_atom_GMZ98.dat',
  'coll': 'c_ii_coll_BP92.dat',
  'rec': 'c_ii_rec_D00.func'},
 'C3': {'atom': 'c_iii_atom_G83-NS78-WFD96.dat',
